# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title GCD and LCM functions
#' @param x A numeric object that can be coerced to integer
#' @param y A numeric object that can be coerced to integer
#' @return The GCD or LCM
#' @rdname gcd_and_lcm
gcd <- function(x, y) {
    .Call(`_Rational_gcd`, x, y)
}

#' @rdname gcd_and_lcm
lcm <- function(x, y) {
    .Call(`_Rational_lcm`, x, y)
}

